clc;
clear;
close all;

modelName = "RetinaAI_Screening_Workflow";

% Create new Simulink model
new_system(modelName);
open_system(modelName);

%% Blocks

add_block("simulink/Sources/Constant", ...
    modelName + "/Patients per Day", ...
    "Value", "100", ...
    "Position", [40 100 150 130]);

add_block("simulink/Math Operations/Gain", ...
    modelName + "/Image Quality Gate", ...
    "Gain", "0.90", ...
    "Position", [220 100 340 130]);

add_block("simulink/Math Operations/Gain", ...
    modelName + "/AI Screening", ...
    "Gain", "0.95", ...
    "Position", [410 100 520 130]);

add_block("simulink/Math Operations/Gain", ...
    modelName + "/Referral Queue", ...
    "Gain", "0.20", ...
    "Position", [590 100 720 130]);

add_block("simulink/Math Operations/Gain", ...
    modelName + "/Doctor Capacity", ...
    "Gain", "0.50", ...
    "Position", [790 100 920 130]);

add_block("simulink/Sinks/Display", ...
    modelName + "/Patients Reviewed", ...
    "Position", [1000 100 1100 140]);

%% Connections

add_line(modelName, ...
    "Patients per Day/1", ...
    "Image Quality Gate/1");

add_line(modelName, ...
    "Image Quality Gate/1", ...
    "AI Screening/1");

add_line(modelName, ...
    "AI Screening/1", ...
    "Referral Queue/1");

add_line(modelName, ...
    "Referral Queue/1", ...
    "Doctor Capacity/1");

add_line(modelName, ...
    "Doctor Capacity/1", ...
    "Patients Reviewed/1");

%% Save

save_system(modelName, ...
    fullfile(pwd, modelName + ".slx"));

fprintf("\n============================================\n");
fprintf(" RetinaAI Simulink Workflow Created\n");
fprintf("============================================\n");
fprintf("Model: %s.slx\n", modelName);
fprintf("============================================\n");